### ISSUE TITLE
Fix image preview

### ISSUE THREAD

**Issue by tracheopteryx** [iearn-finance/ygift-ui#9]
- image doesn't show up in rarible
- enable image previews for twitter, telegram, discord, etc

![unknown](https://user-images.githubusercontent.com/69904756/101190551-cd0aef80-3658-11eb-967e-23e88330a3e9.png)

<img width="522" alt="Screen Shot 2020-12-04 at 5 48 23 PM" src="https://user-images.githubusercontent.com/69904756/101190642-f297f900-3658-11eb-9c10-3ab595d0d8f4.png">

**Comment by ericjuta** [comment]
@tracheopteryx so the rarible thing I'm not sure? 
Do they read from the smart contract or from our site?

Just some personal notes below:
SEO Opengraph + Image previews will require the following:
- [x] migrate the hosting to AWS + domain from namecheap
- [x] rewrite the routing in next.js 
- [x] spend more time doing server side web3 calls
